modLoader="javafml"
loaderVersion="[37,)"
issueTrackerURL="https://github.com/Creators-of-Create/Create/issues"
license="MIT"

[[mods]]
modId="create"
version="0.4"
displayName="Create"
#updateJSONURL=""
displayURL="https://www.curseforge.com/minecraft/mc-mods/create"
logoFile="logo.png"
#credits=""
authors="simibubi"
description='''
Technology that empowers the player.'''

[[dependencies.create]]
    modId="forge"
    mandatory=true
    versionRange="[37.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create]]
    modId="flywheel"
    mandatory=true
    versionRange="[1.17-0.3.0,1.17-0.3.1)"
    ordering="AFTER"
    side="BOTH"
