modLoader="javafml" 
loaderVersion="[28,)" 
#issueTrackerURL=""

[[mods]] 
modId="create"
version="mc1.14-0.2.2"
displayName="Create" 
#updateJSONURL=""
authors="simibubi" 
description='''
Technology that empowers the player.'''

[[dependencies.create]] 
    modId="forge"
    mandatory=true 
    versionRange="[28.1.56,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"